### PR TITLE
Fix signing other http methods than `GET`

### PR DESCRIPTION
**Pull request by bruno-xo7**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Hi @bruno-xo7 

Thanks for creating this issue. It doesn't look like adding the `method` to the `request` before signing changes something to the signature. The tests still succeed. So is it possible that the issue you hit was more about the query params not present?

**Comment by bruno-xo7** [comment]
Hello @SamVerschueren ,

The HTTP method seems to be important for the AWS signature V4 process, as stated in the official documentation: https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html 

Your test succeed because you get the default `GET` method if you don't assign the `method` to the `request`:

* method (will use 'GET' if not given or 'POST' if there is a body) (https://github.com/mhart/aws4#api)

**Comment by SamVerschueren** [comment]
Ah yes, you are right, thanks for clarifying 🙏 .

Would it be able to add an extra test for a `POST` method for instance?

**Comment by bruno-xo7** [comment]
> Would it be able to add an extra test for a `POST` method for instance?
Done. And also one for PATCH method

Could you please publish a new version?

**Review by SamVerschueren — APPROVED** [review]

**Comment by SamVerschueren** [comment]
Released! Thanks for following up on this one!

**Pull request merged**
